import type { Exercise } from "./types";

export const EXERCISES: Exercise[] = [
  // ---------- PUSH ----------
  {
    id: "bench-press",
    name: "Barbell Bench Press",
    muscles: ["chest", "triceps", "shoulders"],
    equipment: ["full"],
    focuses: ["push", "upper", "full"],
    tier: "primary",
    met: 6.0,
    cue: "Tuck elbows ~45°, bar to lower chest, drive feet.",
    defaultReps: 8,
    weighted: true,
  },
  {
    id: "db-bench",
    name: "Dumbbell Bench Press",
    muscles: ["chest", "triceps"],
    equipment: ["full", "dumbbells"],
    focuses: ["push", "upper", "full"],
    tier: "primary",
    met: 5.5,
    cue: "Wrists stacked over elbows, control the eccentric.",
    defaultReps: 10,
    weighted: true,
  },
  {
    id: "ohp",
    name: "Overhead Press",
    muscles: ["shoulders", "triceps"],
    equipment: ["full", "dumbbells"],
    focuses: ["push", "upper"],
    tier: "primary",
    met: 5.5,
    cue: "Brace core, bar finishes over mid-foot, no flared ribs.",
    defaultReps: 8,
    weighted: true,
  },
  {
    id: "incline-db",
    name: "Incline Dumbbell Press",
    muscles: ["chest", "shoulders"],
    equipment: ["full", "dumbbells"],
    focuses: ["push", "upper"],
    tier: "accessory",
    met: 5.0,
    cue: "Bench at 30°. Don't shrug to start the press.",
    defaultReps: 10,
    weighted: true,
  },
  {
    id: "lateral-raise",
    name: "Lateral Raise",
    muscles: ["shoulders"],
    equipment: ["full", "dumbbells"],
    focuses: ["push", "upper"],
    tier: "accessory",
    met: 4.0,
    cue: "Lead with the elbows, pinky slightly up.",
    defaultReps: 12,
    weighted: true,
  },
  {
    id: "tricep-pushdown",
    name: "Tricep Pushdown",
    muscles: ["triceps"],
    equipment: ["full"],
    focuses: ["push", "upper"],
    tier: "accessory",
    met: 4.0,
    cue: "Elbows pinned, full lockout, slow on the way up.",
    defaultReps: 12,
    weighted: true,
  },
  {
    id: "pushup",
    name: "Push-up",
    muscles: ["chest", "triceps", "shoulders", "core"],
    equipment: ["full", "dumbbells", "bodyweight"],
    focuses: ["push", "upper", "full"],
    tier: "accessory",
    met: 5.0,
    cue: "Plank from heels to head, elbows ~45°.",
    defaultReps: 12,
    weighted: false,
  },
  {
    id: "dip",
    name: "Dip",
    muscles: ["chest", "triceps", "shoulders"],
    equipment: ["full", "bodyweight"],
    focuses: ["push", "upper"],
    tier: "accessory",
    met: 5.5,
    cue: "Lean forward for chest, upright for triceps.",
    defaultReps: 8,
    weighted: false,
  },

  // ---------- PULL ----------
  {
    id: "deadlift",
    name: "Conventional Deadlift",
    muscles: ["back", "glutes", "hamstrings"],
    equipment: ["full"],
    focuses: ["pull", "lower", "full"],
    tier: "primary",
    met: 6.5,
    cue: "Bar over mid-foot, lats tight, push the floor away.",
    defaultReps: 5,
    weighted: true,
  },
  {
    id: "pullup",
    name: "Pull-up",
    muscles: ["back", "biceps"],
    equipment: ["full", "bodyweight"],
    focuses: ["pull", "upper"],
    tier: "primary",
    met: 6.0,
    cue: "Pull elbows to ribs, dead-hang at the bottom.",
    defaultReps: 6,
    weighted: false,
  },
  {
    id: "barbell-row",
    name: "Barbell Row",
    muscles: ["back", "biceps"],
    equipment: ["full"],
    focuses: ["pull", "upper", "full"],
    tier: "primary",
    met: 5.5,
    cue: "Flat back, pull to lower ribs, no shrug.",
    defaultReps: 8,
    weighted: true,
  },
  {
    id: "db-row",
    name: "One-Arm Dumbbell Row",
    muscles: ["back", "biceps"],
    equipment: ["full", "dumbbells"],
    focuses: ["pull", "upper"],
    tier: "primary",
    met: 5.0,
    cue: "Hip hinge, row to the hip, squeeze the lat.",
    defaultReps: 10,
    weighted: true,
  },
  {
    id: "lat-pulldown",
    name: "Lat Pulldown",
    muscles: ["back", "biceps"],
    equipment: ["full"],
    focuses: ["pull", "upper"],
    tier: "primary",
    met: 5.0,
    cue: "Lead with the elbows, bar to upper chest.",
    defaultReps: 10,
    weighted: true,
  },
  {
    id: "face-pull",
    name: "Face Pull",
    muscles: ["shoulders", "back"],
    equipment: ["full"],
    focuses: ["pull", "upper"],
    tier: "accessory",
    met: 4.0,
    cue: "Pull to the eyes, externally rotate the shoulders.",
    defaultReps: 15,
    weighted: true,
  },
  {
    id: "db-curl",
    name: "Dumbbell Curl",
    muscles: ["biceps"],
    equipment: ["full", "dumbbells"],
    focuses: ["pull", "upper"],
    tier: "accessory",
    met: 4.0,
    cue: "Elbows quiet at sides, supinate as you lift.",
    defaultReps: 10,
    weighted: true,
  },
  {
    id: "inverted-row",
    name: "Inverted Row",
    muscles: ["back", "biceps"],
    equipment: ["full", "bodyweight"],
    focuses: ["pull", "upper"],
    tier: "accessory",
    met: 4.5,
    cue: "Body rigid plank, pull chest to the bar.",
    defaultReps: 10,
    weighted: false,
  },

  // ---------- LEGS / LOWER ----------
  {
    id: "back-squat",
    name: "Back Squat",
    muscles: ["quads", "glutes"],
    equipment: ["full"],
    focuses: ["legs", "lower", "full"],
    tier: "primary",
    met: 6.0,
    cue: "Knees track toes, sit between the hips, brace hard.",
    defaultReps: 6,
    weighted: true,
  },
  {
    id: "front-squat",
    name: "Front Squat",
    muscles: ["quads", "core"],
    equipment: ["full"],
    focuses: ["legs", "lower"],
    tier: "primary",
    met: 6.0,
    cue: "Elbows up, upright torso, drive knees out.",
    defaultReps: 6,
    weighted: true,
  },
  {
    id: "goblet-squat",
    name: "Goblet Squat",
    muscles: ["quads", "glutes"],
    equipment: ["full", "dumbbells"],
    focuses: ["legs", "lower", "full"],
    tier: "primary",
    met: 5.5,
    cue: "Hold bell at chest, elbows inside the knees at depth.",
    defaultReps: 10,
    weighted: true,
  },
  {
    id: "rdl",
    name: "Romanian Deadlift",
    muscles: ["hamstrings", "glutes", "back"],
    equipment: ["full", "dumbbells"],
    focuses: ["legs", "lower", "pull"],
    tier: "primary",
    met: 5.5,
    cue: "Hinge from the hips, soft knees, bar grazes thighs.",
    defaultReps: 8,
    weighted: true,
  },
  {
    id: "bulgarian",
    name: "Bulgarian Split Squat",
    muscles: ["quads", "glutes"],
    equipment: ["full", "dumbbells", "bodyweight"],
    focuses: ["legs", "lower"],
    tier: "accessory",
    met: 5.5,
    cue: "Front shin vertical at the bottom, weight in mid-foot.",
    defaultReps: 10,
    weighted: true,
  },
  {
    id: "lunge",
    name: "Walking Lunge",
    muscles: ["quads", "glutes"],
    equipment: ["full", "dumbbells", "bodyweight"],
    focuses: ["legs", "lower"],
    tier: "accessory",
    met: 5.0,
    cue: "Long stride, back knee kisses the floor.",
    defaultReps: 12,
    weighted: false,
  },
  {
    id: "leg-curl",
    name: "Leg Curl",
    muscles: ["hamstrings"],
    equipment: ["full"],
    focuses: ["legs", "lower"],
    tier: "accessory",
    met: 4.5,
    cue: "Squeeze the hamstring at the top, slow eccentric.",
    defaultReps: 12,
    weighted: true,
  },
  {
    id: "calf-raise",
    name: "Calf Raise",
    muscles: ["calves"],
    equipment: ["full", "dumbbells", "bodyweight"],
    focuses: ["legs", "lower"],
    tier: "accessory",
    met: 3.5,
    cue: "Full stretch at the bottom, pause hard at the top.",
    defaultReps: 15,
    weighted: false,
  },
  {
    id: "hip-thrust",
    name: "Hip Thrust",
    muscles: ["glutes", "hamstrings"],
    equipment: ["full", "dumbbells", "bodyweight"],
    focuses: ["legs", "lower"],
    tier: "primary",
    met: 5.0,
    cue: "Ribs down, squeeze glutes at lockout, chin tucked.",
    defaultReps: 10,
    weighted: true,
  },

  // ---------- CORE ----------
  {
    id: "plank",
    name: "Plank",
    muscles: ["core"],
    equipment: ["full", "dumbbells", "bodyweight"],
    focuses: ["core", "full"],
    tier: "accessory",
    met: 3.5,
    cue: "Glutes squeezed, ribs down, breathe through it.",
    defaultReps: 45,
    weighted: false,
  },
  {
    id: "hanging-leg-raise",
    name: "Hanging Leg Raise",
    muscles: ["core"],
    equipment: ["full", "bodyweight"],
    focuses: ["core"],
    tier: "primary",
    met: 4.5,
    cue: "Posterior pelvic tilt, no swing, controlled return.",
    defaultReps: 10,
    weighted: false,
  },
  {
    id: "deadbug",
    name: "Dead Bug",
    muscles: ["core"],
    equipment: ["full", "dumbbells", "bodyweight"],
    focuses: ["core"],
    tier: "accessory",
    met: 3.0,
    cue: "Lower back pinned to the floor the entire time.",
    defaultReps: 10,
    weighted: false,
  },
  {
    id: "pallof",
    name: "Pallof Press",
    muscles: ["core"],
    equipment: ["full"],
    focuses: ["core"],
    tier: "accessory",
    met: 3.5,
    cue: "Resist rotation — don't let the cable twist you.",
    defaultReps: 12,
    weighted: true,
  },
  {
    id: "ab-wheel",
    name: "Ab Wheel Rollout",
    muscles: ["core"],
    equipment: ["full", "bodyweight"],
    focuses: ["core"],
    tier: "primary",
    met: 4.5,
    cue: "Hollow body, roll only as far as you can return.",
    defaultReps: 8,
    weighted: false,
  },

  // ---------- CONDITIONING / HIIT ----------
  {
    id: "kb-swing",
    name: "Kettlebell Swing",
    muscles: ["glutes", "hamstrings", "back", "cardio"],
    equipment: ["full", "dumbbells"],
    focuses: ["conditioning", "full"],
    tier: "primary",
    met: 8.0,
    cue: "Hike pass, snap the hips, float not lift.",
    defaultReps: 15,
    weighted: true,
  },
  {
    id: "burpee",
    name: "Burpee",
    muscles: ["chest", "quads", "core", "cardio"],
    equipment: ["full", "dumbbells", "bodyweight"],
    focuses: ["conditioning", "full"],
    tier: "primary",
    met: 8.0,
    cue: "Soft landings, chest taps the floor.",
    defaultReps: 10,
    weighted: false,
  },
  {
    id: "row-machine",
    name: "Rowing Machine (cal)",
    muscles: ["cardio", "back", "quads"],
    equipment: ["full"],
    focuses: ["conditioning"],
    tier: "primary",
    met: 8.5,
    cue: "Legs → back → arms. Reverse on the recovery.",
    defaultReps: 15,
    weighted: false,
  },
  {
    id: "assault-bike",
    name: "Assault Bike (cal)",
    muscles: ["cardio"],
    equipment: ["full"],
    focuses: ["conditioning"],
    tier: "primary",
    met: 9.0,
    cue: "Drive with both arms and legs, breathe through the nose if you can.",
    defaultReps: 12,
    weighted: false,
  },
  {
    id: "mountain-climber",
    name: "Mountain Climber",
    muscles: ["core", "cardio"],
    equipment: ["full", "dumbbells", "bodyweight"],
    focuses: ["conditioning", "core"],
    tier: "accessory",
    met: 8.0,
    cue: "Hips low, drive the knee, breathe.",
    defaultReps: 30,
    weighted: false,
  },
  {
    id: "jump-squat",
    name: "Jump Squat",
    muscles: ["quads", "glutes", "cardio"],
    equipment: ["full", "dumbbells", "bodyweight"],
    focuses: ["conditioning", "lower"],
    tier: "accessory",
    met: 8.0,
    cue: "Soft landings, reset between reps.",
    defaultReps: 12,
    weighted: false,
  },
];

export const WARMUPS: { name: string; sec: number }[] = [
  { name: "Easy cardio (bike/row/jog)", sec: 120 },
  { name: "Hip openers + thoracic rotations", sec: 60 },
  { name: "Dynamic stretch (leg swings, arm circles)", sec: 60 },
  { name: "Activation: 2x10 bodyweight squats + push-ups", sec: 60 },
];

export const COOLDOWNS: { name: string; sec: number }[] = [
  { name: "Walk + deep nasal breathing", sec: 60 },
  { name: "Hold the tightest muscle you trained", sec: 45 },
  { name: "Couch stretch / chest doorway stretch", sec: 45 },
];
